name: Auto Merge Feature Branches

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  auto-merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Auto-merge feature branch
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout main
          git pull origin main
          git merge --no-ff $GITHUB_HEAD_REF
          git push origin main